openapi: 3.0.0
info:
  title: Swagger Petstore
  description: A sample Petstore API
  version: 1.0.0

servers:
  - url: https://petstore.swagger.io/v2
    description: Petstore v2 server

paths:
  /pet/findByStatus:
    get:
      summary: Finds Pets by status
      description: Multiple status values can be provided
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values to filter by
          required: false
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid status value

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    
    Pet:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
          example: 10
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
